### ISSUE TITLE
Level 2 and 4: Create moving obstacle

### ISSUE THREAD

**Issue by tienlocnguyen** [T4g1/gd-wildjam18#35]
Implement moving obstacle list this:
![image](https://user-images.githubusercontent.com/6823008/74699589-a8619a80-5233-11ea-80c7-df6733352cbc.png)
It has exported speed, will moving horizontally, can stop when:
1. Request stop from outside, by function call
2. Player die. This one can remove, use 1 instead to decoupling player and obstacle
3. After fixed time
4. When collide with special kind of physic body(can configured by exported value)

**Comment by T4g1** [comment]
For the level 2 I was thinking about a tsunami so i don't think it should stop when player dies: The death would be like the tsunami goes over the player and after a short delay, level restart (with some transition)

In fact, we should probably use a Path2D to delimit the start and the end of this obstacle so it can stop only when it reaches the end of the path because it wouldn't make sense for the player to see a tsunami wave stops

**Comment by tienlocnguyen** [comment]
I started work on branch running_home_level.
When using Path2D, the path will be created in level design. So I created level too. 
The level is not complete yet and has some bugs. Will continue implement it tomorrow
Currently, tsunami is PathFollow2D and when design level, it will be added as child of Path2D. I'm thinking about add PathFollow2D by code instead of by editor and tsunami can become common Node2D(may be inherit from obstacle)

**Comment by T4g1** [comment]
Yes, I saw it already, you should create a pull request so we can discuss details there. There's no need for a countdown, it feels arbitrary and cheap. We will simply offscreen the tsunami at level start then, we will trigger it when player goes through an arbitrary trigger (already implemented as Interactable). Don't make the assumption it's a tsunami too. It will be a tornado in fact for level 2 and a tsunami for level 4.

**Comment by tienlocnguyen** [comment]
I created PR: https://github.com/T4g1/gd-wildjam18/pull/41
